/**
 * sprite.ts — sprite atlas loader + frame renderer (PRD §3.1).
 * The atlas is embedded as base64 (generated by scripts/generate-sprites.py),
 * so the runtime needs zero binary assets and zero network fetches.
 */

import { ATLAS_B64, FRAMES, CELL } from './sprite-data.js';

let atlas: HTMLImageElement | null = null;

export function loadAtlas(): Promise<void> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      atlas = img;
      resolve();
    };
    img.onerror = () => reject(new Error('hero atlas failed to decode'));
    img.src = 'data:image/png;base64,' + ATLAS_B64;
  });
}

export interface FrameOptions {
  flip?: boolean;
  rotation?: number; // radians
  pivotY?: number;   // rotation pivot relative to the feet anchor (≤ 0)
}

/** draw a 64×64 frame with its feet anchored at (x, yBottom) */
export function drawFrame(
  ctx: CanvasRenderingContext2D,
  name: string,
  x: number,
  yBottom: number,
  opts: FrameOptions = {},
): void {
  const f = FRAMES[name];
  if (!f || !atlas) return;
  const pivotY = opts.pivotY ?? 0;
  ctx.save();
  ctx.translate(Math.round(x), Math.round(yBottom));
  ctx.translate(0, pivotY);
  if (opts.rotation) ctx.rotate(opts.rotation);
  ctx.translate(0, -pivotY);
  if (opts.flip) ctx.scale(-1, 1);
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(atlas, f.x, f.y, CELL, CELL, -CELL / 2, -CELL, CELL, CELL);
  ctx.restore();
}
