/** GENERATED by scripts/extract-walk.py — real walk-art metadata.
    The PNG itself is binary: ships in the zip, regenerated via
    `npm run sprites:walk`. */
export const WALK_ART_URL = '/assets/walk-sheet.png';
export const WALK_ART_CELL = 128;
export const WALK_ART_FPS = 24;

export const WALK_ART_FRAMES: Record<string, { x: number; y: number }> = {
  walk0: { x: 0, y: 0 },
  walk1: { x: 128, y: 0 },
  walk2: { x: 256, y: 0 },
  walk3: { x: 384, y: 0 },
  walk4: { x: 512, y: 0 },
  walk5: { x: 640, y: 0 },
  walk6: { x: 768, y: 0 },
  walk7: { x: 896, y: 0 },
  walk8: { x: 1024, y: 0 },
  walk9: { x: 0, y: 128 },
  walk10: { x: 128, y: 128 },
  walk11: { x: 256, y: 128 },
  walk12: { x: 384, y: 128 },
  walk13: { x: 512, y: 128 },
  walk14: { x: 640, y: 128 },
  walk15: { x: 768, y: 128 },
  walk16: { x: 896, y: 128 },
  walk17: { x: 1024, y: 128 },
};

export const WALK_ART_ANIM: string[] = ["walk0", "walk1", "walk2", "walk3", "walk4", "walk5", "walk6", "walk7", "walk8", "walk9", "walk10", "walk11", "walk12", "walk13", "walk14", "walk15", "walk16", "walk17"];
