#!/usr/bin/env python3
"""
extract-walk.py — cuts the real walking frames from the reference strip
(assets/src-sheets/walk-strip.png: a 9x2 grid on pure black), keys out the
background, normalizes each frame into a 128x128 cell (feet anchored), and
packs a walk atlas.

Outputs:
  public/assets/walk-sheet.png         walk atlas (served at /assets/walk-sheet.png)
  assets/sprites/walk-sheet.png        copy for the record
  assets/sprites/walk-sheet.json       frame + animation descriptor
  src/hero/animation/walk-art-data.ts  frame metadata (text — safe for git; the
                                       PNG ships in the zip / drop it into
                                       public/assets/ manually)

Run:  python3 scripts/extract-walk.py   (or: npm run sprites:walk)
"""

import json
import os

import cv2
import numpy as np
from PIL import Image, ImageFilter

SRC = 'assets/src-sheets/walk-strip.png'
CELL = 128
FPS = 24
COLS = 9
ROWS = 2
CHAR_H = 112   # character height inside a cell
FEET_Y = 126   # feet line inside a cell


def main():
    img = Image.open(SRC).convert('RGB')
    W, H = img.size
    cw, ch = W // COLS, H // ROWS
    print(f'strip: {W}x{H} -> {COLS}x{ROWS} grid of {cw}x{ch} cells')

    frames = []
    for r in range(ROWS):
        for c in range(COLS):
            cell = img.crop((c * cw, r * ch, (c + 1) * cw, (r + 1) * ch))
            a = np.asarray(cell).astype(np.int16)
            v = a.max(axis=2).astype(np.float32)
            # the backdrop is near-black (~12/255) with noise up to ~15 and
            # the dark suit sits just above it — so threshold low, then
            # recover the matte: close rim gaps, flood-fill interior holes
            # (dark torso etc.), keep the character blob, drop specks
            corners = np.concatenate([
                v[:6, :6].ravel(), v[:6, -6:].ravel(),
                v[-6:, :6].ravel(), v[-6:, -6:].ravel(),
            ])
            bg = float(np.median(corners))
            mask = (v > max(15.0, bg + 3)).astype(np.uint8)
            mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE,
                                    np.ones((5, 5), np.uint8), iterations=2)
            ff = (mask * 255).copy()
            ffmask = np.zeros((ff.shape[0] + 2, ff.shape[1] + 2), np.uint8)
            cv2.floodFill(ff, ffmask, (0, 0), 128)
            mask = np.clip(mask + (ff == 0).astype(np.uint8), 0, 1)
            n, lab, stats, _ = cv2.connectedComponentsWithStats(mask, 8)
            if n > 1:
                areas = stats[1:, cv2.CC_STAT_AREA]
                keep = {1 + int(np.argmax(areas))}
                for i, ar in enumerate(areas):
                    if ar >= max(250, 0.02 * areas.max()):
                        keep.add(1 + i)
                mask = np.isin(lab, list(keep)).astype(np.uint8)

            ys, xs = np.nonzero(mask)
            if len(xs) < 50:
                print(f'  warn: cell r{r}c{c} looks empty, skipped')
                continue
            x0, x1, y0, y1 = int(xs.min()), int(xs.max()), int(ys.min()), int(ys.max())

            alpha = Image.fromarray((mask * 255).astype(np.uint8)).filter(
                ImageFilter.GaussianBlur(0.8)
            )
            rgba = np.dstack([np.asarray(cell), np.asarray(alpha)])
            frame = Image.fromarray(rgba, 'RGBA').crop((x0, y0, x1 + 1, y1 + 1))
            frames.append(frame)

    print(f'extracted {len(frames)} walk frames')

    # normalize into cells, feet anchored at the bottom
    cells = []
    for f in frames:
        w, h = f.size
        s = min(CHAR_H / h, 120 / w)
        nw, nh = max(1, int(w * s)), max(1, int(h * s))
        f = f.resize((nw, nh), Image.LANCZOS)
        cell = Image.new('RGBA', (CELL, CELL), (0, 0, 0, 0))
        cell.paste(f, ((CELL - nw) // 2, FEET_Y - nh), f)
        cells.append(cell)

    rows = (len(cells) + COLS - 1) // COLS
    atlas = Image.new('RGBA', (COLS * CELL, rows * CELL), (0, 0, 0, 0))
    meta = {}
    for i, cimg in enumerate(cells):
        x, y = (i % COLS) * CELL, (i // COLS) * CELL
        atlas.paste(cimg, (x, y), cimg)
        meta[f'walk{i}'] = {'x': x, 'y': y}

    os.makedirs('public/assets', exist_ok=True)
    os.makedirs('assets/sprites', exist_ok=True)
    os.makedirs('src/hero/animation', exist_ok=True)
    atlas.save('public/assets/walk-sheet.png', optimize=True)
    atlas.save('assets/sprites/walk-sheet.png', optimize=True)

    names = list(meta.keys())
    with open('assets/sprites/walk-sheet.json', 'w') as f:
        json.dump({'frames': meta, 'animations': {'walk': names},
                   'meta': {'fps': FPS, 'cell': CELL}}, f, indent=1)

    ts = [
        '/** GENERATED by scripts/extract-walk.py — real walk-art metadata.',
        '    The PNG itself is binary: ships in the zip, regenerated via',
        '    `npm run sprites:walk`. */',
        "export const WALK_ART_URL = '/assets/walk-sheet.png';",
        f'export const WALK_ART_CELL = {CELL};',
        f'export const WALK_ART_FPS = {FPS};',
        '',
        'export const WALK_ART_FRAMES: Record<string, { x: number; y: number }> = {',
    ]
    for name, m in meta.items():
        ts.append(f"  {name}: {{ x: {m['x']}, y: {m['y']} }},")
    ts.append('};')
    ts.append('')
    ts.append(f'export const WALK_ART_ANIM: string[] = {json.dumps(names)};')
    ts.append('')
    with open('src/hero/animation/walk-art-data.ts', 'w') as f:
        f.write('\n'.join(ts))

    kb = os.path.getsize('public/assets/walk-sheet.png') // 1024
    print(f'walk atlas: {atlas.size[0]}x{atlas.size[1]}, {len(cells)} frames, {kb} KB')


if __name__ == '__main__':
    main()
